import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import PublicNavigation from './PublicNavigation.jsx'

const original = { id: 'labelcesty00001', name: 'Cesty & příběhy', slug: 'cesty', color: '#B88A36' }
const view = (labels, props = {}, route = '/') => <MemoryRouter initialEntries={[route]}><PublicNavigation labels={labels} {...props} /></MemoryRouter>

it('rozbalí Blog bez chevronu, dodrží pořadí a ukáže aktuální názvy bez barevných proužků', async () => {
  const user = userEvent.setup()
  const { rerender } = render(view([original]))
  expect([...document.querySelectorAll('.public-navigation-link')].map((item) => item.textContent)).toEqual(['DOMŮ', 'Blog', 'GALERIE', 'O MNĚ', 'KONTAKT'])
  expect(screen.queryByRole('link', { name: original.name })).not.toBeInTheDocument()
  const toggle = screen.getByRole('button', { name: 'Blog', exact: true })
  expect(toggle.querySelector('svg')).toBeNull()
  expect(screen.queryByRole('link', { name: 'Blog', exact: true })).not.toBeInTheDocument()
  toggle.focus()
  await user.keyboard('{Enter}')
  expect(toggle).toHaveAttribute('aria-expanded', 'true')
  const oldLink = screen.getByRole('link', { name: original.name })
  expect(oldLink).toHaveAttribute('href', '/blog?label=cesty')
  rerender(view([{ ...original, name: 'Moje putování', color: '#ABCDEF' }]))
  expect(screen.queryByText(original.name)).not.toBeInTheDocument()
  const link = screen.getByRole('link', { name: 'Moje putování' })
  expect(link).toHaveAttribute('href', '/blog?label=cesty')
  expect(link).not.toHaveAttribute('style')
  await user.tab()
  expect(screen.getByRole('link', { name: 'Všechny články' })).toHaveFocus()
  expect(screen.getByRole('link', { name: 'Všechny články' })).toHaveAttribute('href', '/blog')
  await user.tab()
  expect(link).toHaveFocus()
  await user.keyboard('{Escape}')
  expect(toggle).toHaveFocus()
  expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await user.keyboard(' ')
  await user.click(screen.getByRole('link', { name: 'Všechny články' }))
  expect(toggle).toHaveAttribute('aria-expanded', 'true')
  expect(toggle).toHaveAttribute('aria-disabled', 'true')
})

it.each(['/blog', '/blog?label=cesty', '/blog/prvni-clanek'])('na %s ponechá podkategorie otevřené i po kliku, klávesnici a změně filtru', async (route) => {
  const user = userEvent.setup()
  render(view([original], {}, route))
  const toggle = screen.getByRole('button', { name: 'Blog', exact: true })
  expect(toggle).toHaveAttribute('aria-expanded', 'true')
  expect(toggle).toHaveAttribute('aria-disabled', 'true')
  expect(screen.getByRole('link', { name: original.name })).toBeVisible()
  await user.click(toggle)
  toggle.focus()
  await user.keyboard('{Enter} {Escape}')
  expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await user.tab()
  expect(screen.getByRole('link', { name: 'Všechny články' })).toHaveFocus()
  await user.click(screen.getByRole('link', { name: original.name }))
  expect(screen.getByRole('link', { name: original.name })).toHaveAttribute('aria-current', 'page')
  expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await user.click(screen.getByRole('link', { name: 'GALERIE' }))
  expect(toggle).toHaveAttribute('aria-expanded', 'false')
  expect(toggle).not.toHaveAttribute('aria-disabled')
  await user.click(toggle)
  expect(screen.getByRole('link', { name: original.name })).toBeVisible()
})

it('empty a error stav neblokují odkaz na celý blog', async () => {
  const user = userEvent.setup()
  const retry = vi.fn()
  const { rerender } = render(view([]))
  await user.click(screen.getByRole('button', { name: 'Blog', exact: true }))
  expect(screen.getByText('Zatím žádné štítky.')).toBeVisible()
  rerender(view([], { state: 'network', onRetry: retry }))
  await user.click(screen.getByRole('button', { name: 'Zkusit znovu' }))
  expect(retry).toHaveBeenCalledOnce()
  expect(screen.getByRole('link', { name: 'Všechny články' })).toHaveAttribute('href', '/blog')
})
